-- MySQL Script generated by MySQL Workbench
-- jue 09 nov 2017 01:17:11 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema secretsharing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secretsharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secretsharing` DEFAULT CHARACTER SET latin1 ;
USE `secretsharing` ;

-- -----------------------------------------------------
-- Table `secretsharing`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsharing`.`usuario` (
  `idUsuario` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `espacioUtilizado` BIGINT(20) NOT NULL DEFAULT 0,
  `urlRecuperacion` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secretsharing`.`carpeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsharing`.`carpeta` (
  `idCarpeta` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(255) NOT NULL,
  `idCarpetaSuperior` INT(11) NULL DEFAULT NULL,
  `nombreCarpeta` VARCHAR(255) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  PRIMARY KEY (`idCarpeta`, `idUsuario`),
  INDEX `fk_Carpeta_Carpeta_idx` (`idCarpetaSuperior` ASC),
  INDEX `fk_Carpeta_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Carpeta_Carpeta`
    FOREIGN KEY (`idCarpetaSuperior`)
    REFERENCES `secretsharing`.`carpeta` (`idCarpeta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Carpeta_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `secretsharing`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secretsharing`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsharing`.`archivo` (
  `nombreArchivo` VARCHAR(255) NOT NULL,
  `idCarpeta` INT(11) NOT NULL,
  `idUsuario` VARCHAR(255) NOT NULL,
  `nombreArchivoGRID` VARCHAR(300) NOT NULL,
  `tamanio` INT(11) NOT NULL,
  `fechaSubida` DATE NOT NULL,
  PRIMARY KEY (`nombreArchivo`, `idCarpeta`, `idUsuario`),
  INDEX `fk_Archivo_Carpeta1_idx` (`idCarpeta` ASC, `idUsuario` ASC),
  CONSTRAINT `fk_Archivo_Carpeta1`
    FOREIGN KEY (`idCarpeta` , `idUsuario`)
    REFERENCES `secretsharing`.`carpeta` (`idCarpeta` , `idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
