all: BorraArchivo BorraCarpeta

BorraArchivo: BorraArchivo.cpp
	g++ -std=c++0x -g2 -O2 -Wall -Wextra -Wno-unused "BorraArchivo.cpp" -o BorraArchivo
	
BorraCarpeta: BorraCarpeta.cpp
	g++ -std=c++0x -g2 -O2 -Wall -Wextra -Wno-unused "BorraCarpeta.cpp" -o BorraCarpeta 
